replicaCount: 1

image:
  repository: "localhost:32000/frontend"
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 3000

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

env:
  REACT_APP_API_URL: "http://10.152.183.114:3001/api"

hpa:
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 60
