replicaCount: 1

image:
  repository: localhost:32000/frontend
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 3000

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
