replicaCount: 1

image:
  repository: "localhost:32000/frontend"
  tag: v10
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 3000

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

env:
  REACT_APP_API_URL: "http://10.1.83.194:3001/api"
