replicaCount: 1

image:
  repository: container-registry.registry.svc.local:3200/frontend
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 3000

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
