replicaCount: 1

image:
  repository: container-registry.registry.svc.local:3200/web
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 3000
  nodePort: 30000

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
