replicaCount: 1

image:
  repository: localhost:32000/backend
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 3001

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}


mongodb:
  auth:
    username: username
    password: password
    database: todos
  primary:
    persistence:
      enabled: true
      size: 8Gi
  service:
    port: 27017

hpa:
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 60
